import unittest
from drive_by_wire import *
class TestDriveByWire(unittest.TestCase):
    def test_drive_by_wire(self):
        drive_by_wire = DriveByWire()
        self.assertFalse(drive_by_wire.get_status())
        drive_by_wire.on()
        self.assertTrue(drive_by_wire.get_status())
        drive_by_wire.off()
        self.assertFalse(drive_by_wire.get_status())
        drive_by_wire.on()
        self.assertTrue(drive_by_wire.get_status())
        drive_by_wire.brake()
    def test_propulsion(self):
        propulsion = Propulsion()
        self.assertFalse(propulsion.get_status())
        propulsion.on()
        self.assertTrue(propulsion.get_status())
        propulsion.off()
        self.assertFalse(propulsion.get_status())
        propulsion.on()
        self.assertTrue(propulsion.get_status())
        propulsion.set_rotation_speed(100)
        self.assertEqual(propulsion.feedback(), "Brake is being applied")
        propulsion.brake()
        self.assertEqual(propulsion.feedback(), "Brake applied successfully")
    def test_wheels(self):
        wheels = Wheels()
        wheels.set_rotation_speed(100)
        self.assertEqual(wheels.get_rotation_speed(), 100)
        wheels.brake()
        self.assertEqual(wheels.get_rotation_speed(), 0)
        self.assertEqual(wheels.feedback(), "Brake applied successfully")
    def test_transmission(self):
        transmission = Transmission()
        transmission.set_gear(1)
        self.assertEqual(transmission.get_gear(), 1)
        transmission.set_gear(2)
        self.assertEqual(transmission.get_gear(), 2)
        transmission.set_gear(3)
        self.assertEqual(transmission.get_gear(), 3)
        transmission.set_gear(4)
        self.assertEqual(transmission.get_gear(), 4)
        transmission.set_gear(5)
        self.assertEqual(transmission.get_gear(), 5)
        transmission.set_gear(6)
        self.assertEqual(transmission.get_gear(), 6)
    def test_drive_by_wire_init(self):
        drive_by_wire = DriveByWire()
        self.assertFalse(drive_by_wire.get_status())
        self.assertEqual(drive_by_wire.get_gear(), 0)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
    def test_drive_by_wire_accelerate(self):
        drive_by_wire = DriveByWire()
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 200)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 300)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 400)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 500)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 600)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 700)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 800)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 900)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 1000)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 1000)        
    def test_drive_by_wire_steer(self):
        drive_by_wire = DriveByWire()
        drive_by_wire.steer(10)
        self.assertEqual(drive_by_wire.get_gear(), 1)
        drive_by_wire.steer(20)
        self.assertEqual(drive_by_wire.get_gear(), 2)
        drive_by_wire.steer(30)
        self.assertEqual(drive_by_wire.get_gear(), 3)
        drive_by_wire.steer(40)
        self.assertEqual(drive_by_wire.get_gear(), 4)
        drive_by_wire.steer(50)
        self.assertEqual(drive_by_wire.get_gear(), 5)
        drive_by_wire.steer(60)
        self.assertEqual(drive_by_wire.get_gear(), 6)
        drive_by_wire.steer(70)
        self.assertEqual(drive_by_wire.get_gear(), 6)
        drive_by_wire.steer(60)
        self.assertEqual(drive_by_wire.get_gear(), 5)
        drive_by_wire.steer(50)
        self.assertEqual(drive_by_wire.get_gear(), 4)
        drive_by_wire.steer(40)
        self.assertEqual(drive_by_wire.get_gear(), 3)
        drive_by_wire.steer(30)
        self.assertEqual(drive_by_wire.get_gear(), 2)
        drive_by_wire.steer(20)
        self.assertEqual(drive_by_wire.get_gear(), 1)
        drive_by_wire.steer(10)
        self.assertEqual(drive_by_wire.get_gear(), 1)
    def test_drive_by_wire_brake(self):
        drive_by_wire = DriveByWire()
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
        drive_by_wire.accelerate(100)
        self.assertEqual(drive_by_wire.get_rotation_speed(), 100)
        drive_by_wire.brake()
        self.assertEqual(drive_by_wire.get_rotation_speed(), 0)
    def test_gear(self):
        gear = Gear()
        gear.set_gear(1)
        self.assertEqual(gear.get_gear(), 1)
        gear.set_gear(2)
        self.assertEqual(gear.get_gear(), 2)
        gear.set_gear(3)
        self.assertEqual(gear.get_gear(), 3)
def main():
    unittest.main()    
if __name__ == '__main__':
    main()

